body:
  - type: input
    id: konsist-version
    attributes:
      label: Tell us what version of Konsist you use.
    validations:
      required: true

  - type: dropdown
    id: regression-error
    attributes:
      label: Was this something which used to work for you, and then stopped?
      options:
        - 'Placeholder value, please select the correct response from the dropdown'
        - 'I am trying to get this working for the first time'
        - 'It used to work, and then stopped'
    validations:
      required: true

  - type: textarea
    id: describe-problem
    attributes:
      label: Describe the problem
      description: 'Place a Konsist test here and Kotlin code snippet to help us reproduce the problem.'
    validations:
      required: true
    value: |
        I'm writing this Konsist test:
        
        To test this Kotlin code:

  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
      description: 'Describe the current behavior.'
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: 'Describe the expected behavior.'
    validations:
      required: true

    validations:
      required: false
