body:
  - type: input
    id: konsist-version
    attributes:
      label: Tell us what version of Konsist you use.
    validations:
      required: true

  - type: dropdown
    id: regression-error
    attributes:
      label: Was this something which used to work for you, and then stopped?
      options:
        - 'Placeholder value, please select the correct response from the dropdown'
        - 'I am trying to get this working for the first time'
        - 'It used to work, and then stopped'
    validations:
      required: true

  - type: textarea
    id: describe-problem
    attributes:
      label: Describe the problem
    validations:
      required: true

  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
      description: 'Describe the current behavior.'
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: 'Describe the expected behavior.'
    validations:
      required: true

  - type: textarea
    id:  code-snippet
    attributes:
      label: Relevant code snippet.
      description: 'You can place a Konsist test here and simplified Kotlin files to help us reproduce the problem.'
      value: |
        ```kotlin
        Copy/paste the code snippet here, between the starting and ending backticks
        ```

        </details>
    validations:
      required: false
