package com.lemonappdev.konsist.core.provider

import com.lemonappdev.konsist.api.provider.KoKDocTagNameAndDescriptionProvider

internal interface KoKDocTagNameAndDescriptionProviderCore : KoKDocTagNameAndDescriptionProvider
