name: Check Starter Projects (By Path Trigger)

on:
  pull_request:
    types: [ opened, synchronize ]
    paths:
      - 'samples/starter-projects/**'

jobs:
  konsist-starter-android-gradle-groovy-junit-4:
    name: Konsist Starter Android Gradle Groovy Junit 4
    uses: .github/workflows/check-starter-projects.yml
