name: Check

on:
  push:
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'docs/**'
    types: [ opened, synchronize ]

jobs:
  spring-gradle-groovy-junit-5:
    name: spring-gradle-groovy-junit-5
    continue-on-error: true
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'zulu'

      - name: spring-gradle-groovy-junit-5
        run: cd samples/projects/spring-gradle-groovy-junit-5 && ./gradlew konsistTest

  spring-gradle-kotlin-junit-5:
    name: spring-gradle-kotlin-junit-5
    continue-on-error: true
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'zulu'

      - name: spring-gradle-kotlin-junit-5
        run: cd samples/projects/spring-gradle-kotlin-junit-5 && ./gradlew konsistTest

  spring-maven-junit5:
    name: spring-maven-junit5
    continue-on-error: true
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'zulu'

      - name: spring-maven-junit5
        run: cd samples/projects/spring-maven-junit5 && mvn test

  android-gradle-groovy-junit-4:
    name: android-gradle-groovy-junit-4
    continue-on-error: true
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'zulu'

      - name: android-gradle-groovy-junit-4
        run: cd samples/projects/android-gradle-groovy-junit-4 && ./gradlew test


  android-gradle-groovy-junit-5:
    name: android-gradle-groovy-junit-5
    continue-on-error: true
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'zulu'

      - name: android-gradle-groovy-junit-5
        run: cd samples/projects/android-gradle-groovy-junit-5 && ./gradlew test


  android-gradle-kotlin-junit-4:
    name: android-gradle-kotlin-junit-4
    continue-on-error: true
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'zulu'

      - name: android-gradle-kotlin-junit-4
        run: cd samples/projects/android-gradle-kotlin-junit-4 && ./gradlew test


  android-gradle-kotlin-junit-5:
    name: android-gradle-kotlin-junit-5
    continue-on-error: true
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'zulu'

      - name: android-gradle-kotlin-junit-5
        run: cd samples/projects/android-gradle-kotlin-junit-5 && ./gradlew test
