name: Check Snippet ktdoc Snippets

on:
  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-github-context:
    name: Get Branches
    runs-on: ubuntu-latest

    # Allow the workflow to read the contents of the repository and pull request to be
    # able to retrieve list of changed files when PR is opened from forked repository.
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: List Branches
        run: |
          echo current branch: ${{ steps.branch-name.outputs.current_branch }}
          echo base ref branch branch: ${{ steps.branch-name.outputs.base_ref_branch }}
          echo default branch: ${{ steps.branch-name.outputs.default_branch }}

    outputs:
      current_branch: ${{ steps.branch-name.outputs.current_branch }}
      base_ref_branch: ${{ steps.branch-name.outputs.base_ref_branch }}
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}

  check-ktdoc-snippets:
    name: Check ktdoc Snippets
    needs: get-github-context
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Run Python Script for All Files
        run: python3 scripts/check_ktdoc_snippets.py -all
