[versions]
kotlinVersion = "1.8.22"

[libraries]
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlinVersion" }
junitJupiterEngine = "org.junit.jupiter:junit-jupiter-engine:5.9.3"
kluent = "org.amshove.kluent:kluent:1.72"
# Newest version will be retrieved from mavenLocal (exclusiveContent)
konsist = "com.lemonappdev:konsist:+"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
testLogger = "com.adarshr.test-logger:3.2.0"
